--
--return {
--  "iagorrr/noctishc.nvim",
--  lazy = false,
--  priority = 1000,
--  config = function() vim.cmd("colorscheme noctishc") end
--}
--return {
--  'nyngwang/nvimgelion',
--  config = function()
--    -- do whatever you want for further customization~
--    vim.cmd("colorscheme nvimgelion")
--  end
--}

-- return {
--   "nyoom-engineering/oxocarbon.nvim",
--   lazy = false,
--   priority = 1000,
--   config = function()
--     vim.o.background = "dark" -- set this to dark or light
--     vim.cmd("colorscheme oxocarbon")
--   end
-- }

